package constants

const (
	PATH_STRAPI_CLASS_ROOM          = "PATH_STRAPI_CLASS_ROOM"
	HOST_STRAPI_SERVICE             = "HOST_STRAPI_SERVICE"
	PATH_STRAPI_INFORMATION_GATEWAY = "PATH_STRAPI_INFORMATION_GATEWAY"
)
